openapi: "3.0.0"
info:
  version: 0.0.1
  title: comments
  description: comments api
  contact:
    url: http://skillfactory/

servers:
  - url: /api

tags:
  - name: comments

paths:
  /comments:

    get:
      description: Get all comments.
      operationId: getAllComments
      tags:
        - comments
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

    post:
      description: Create comment.
      operationId: createComment
      tags:
        - comments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComment'
      responses:
        '200':
          description: ok

  /swagger:
    get:
      description: Swagger file
      operationId: getSwagger
      tags:
        - probe
      responses:
        '200':
          description: content of swagger file

components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
          description: ID of the comment
        news_id:
          type: integer
          description: ID of the associated news item
        parent_comment_id:
          type: integer
          description: ID of the parent comment (if any)
          nullable: true
        content:
          type: string
          description: Content of the comment
      required:
        - id 
        - news_id
        - content

    CreateComment:
      type: object
      properties:
        news_id:
          type: integer
          description: ID of the associated news item
        parent_comment_id:
          type: integer
          description: ID of the parent comment (if any)
          nullable: true
        content:
          type: string
          description: Content of the comment
      required:
        - news_id
        - content
